description = "Tiny base image (Ubuntu Jammy Jellyfish build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."


# Targets the buildpack will work with
[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[lifecycle]
  version = "0.19.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build-jammy-tiny:0.2.29"
  id = "io.buildpacks.stacks.jammy.tiny"
  run-image = "index.docker.io/paketobuildpacks/run-jammy-tiny:latest"
  run-image-mirrors = []
